
name: LinkTicEcommerBackCI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: azure/docker-login@v1
        with:
          login-serve: acreastest.azurecr.io
          username: ${{secret.ACR_USERNAME}}
          password: ${{secret.ACR_PASSWORDUSER}}
      - run: |
        docker build . -t acreastest.azurecr.io/ecommercetic-back:${{github.sha}}
        docker push acreastest.azurecr.io/ecommercetic-back:${{github.sha}}
