
name: LinkTicEcommerBackCI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
  
      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      - uses: actions/checkout@v4
      - uses: azure/docker-login@v1
        with:
          login-serve: acreastest.azurecr.io
          username: ${{secrets.ACR_USERNAME}}
          password: ${{secrets.ACR_PASSWORDUSER}}
      - run: |
          docker build . -t acreastest.azurecr.io/ecommercetic-back:${{github.sha}}
          docker push acreastest.azurecr.io/ecommercetic-back:${{github.sha}}
